import type { Metadata } from "next";
import {ClerkProvider} from "@clerk/nextjs";
import "./globals.css";
import { ModalProvider } from "@/providers/modal-provider";
import { ToasterProvider } from "@/providers/toast-provider";


export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html>
        
        <body>
          <ToasterProvider/>
          <ModalProvider/>
          {children}
        </body>
        
      </html>
    </ClerkProvider>
      
    
  );
}
